[package]
name = "canvas_finalproject"
version = "0.1.0"
authors = ["Andres Kim <andreskim2018@u.northwestern.edu>"]

[dependencies]
rgb = "0.8"
ws = "*"
json = "*"
sharing_is_caring = { path = "../server-lib" }
